add home work number ten
IvanKeyiOS/homeWorks pull request #10
Opened 2024-11-17 14:52 UTC by IvanKeyiOS

2024-11-17 14:55 UTC, IvanKeyiOS commented
Здравствуйте, Юля!

не уверен верно ли понял и соответстевенно выполнил вот это задание -> Напишите функцию, которая отсортирует массив на разные массивы по должностям (т.е. нападающие в отдельный и т.д.)

Буду ждать твоих комментариев, заранее спасибо

2024-11-17 23:34 UTC, LiyaNova requested changes
Ваня, не внимательно читаешь ТЗ😉 Не торопись, если условие задачи не до конца понятно, то лучше написать мне и спросить.

2024-11-17 23:34 UTC, LiyaNova commented on 10_FunctionalProgramming.playground/Contents.swift
> +    let position: String
Все-таки позиция это какой-то фиксированный список. Какой тип данных лучше использовать в таком случае?

2024-11-17 23:34 UTC, LiyaNova commented on 10_FunctionalProgramming.playground/Contents.swift
> +bocaJuniors.enumerated().forEach { print("\($0) \($1)") }
Обрати внимание на задание: напишите функцию, которая принимает массив игроков и печатает в консоль их данные. А не распечатайте массив игроков)

2024-11-17 23:34 UTC, LiyaNova commented on 10_FunctionalProgramming.playground/Contents.swift
> +let sortSureName: [FootballPlayer] = bocaJuniors.sorted { $0.surename < $1.surename }
Чего-то не хватает: Если фамилии одинаковые, сравнивайте по имени. Нужно усложнить условие сортировки

2024-11-17 23:34 UTC, LiyaNova commented on 10_FunctionalProgramming.playground/Contents.swift
> +let goalkeaper: [FootballPlayer] = bocaJuniors.filter { $0.position == "Goalkeaper" }
Здесь снова обрати внимание на задание:  Напишите функцию, которая отсортирует массив.
То есть тебе нужно написать алгоритм (функцию), который выполнит данное условие.

2024-11-17 23:34 UTC, LiyaNova commented on 10_FunctionalProgramming.playground/Contents.swift
> +let overalGoalsAmount: Int = goalsAmont.reduce(0, { $0 + $1 } )
Можно также более коротко: goalsAmont.reduce(0, +)

2024-11-18 05:16 UTC, IvanKeyiOS commented on 10_FunctionalProgramming.playground/Contents.swift
> +    let position: String
Enum

2024-11-18 05:18 UTC, IvanKeyiOS commented on 10_FunctionalProgramming.playground/Contents.swift
> +let sortSureName: [FootballPlayer] = bocaJuniors.sorted { $0.surename < $1.surename }
Да, полностью согласен

2024-11-18 05:18 UTC, IvanKeyiOS commented on 10_FunctionalProgramming.playground/Contents.swift
> +bocaJuniors.enumerated().forEach { print("\($0) \($1)") }
Окей

2024-11-19 21:55 UTC, IvanKeyiOS commented
Привет! 
Надеюсь так выглядит лучше и правильнее.
Сори если вновь что-то не так.

2024-11-20 04:24 UTC, LiyaNova requested changes
Ваня, молодец! Не нужно извинять за правки 😉 Ты все делаешь хорошо, шаг за шагом. Предлагаю сделать еще один шажок в это задании

2024-11-20 04:24 UTC, LiyaNova commented on 10_FunctionalProgramming.playground/Contents.swift
> +enum Position: String {
Молодец!

2024-11-20 04:24 UTC, LiyaNova commented on 10_FunctionalProgramming.playground/Contents.swift
> +let sortSureName: [FootballPlayer] = bocaJuniors.sorted { $0.name < $1.name }.sorted { $0.surename < $1.surename }
Не нужно сортировать несколько раз. Это не оптимально. Свифт позволяет сделать все проверки в рамках одной сортировки

```
let playersSortedByName = footballTeam.sorted { (firstPlayer, secondPlayer) in
    if firstPlayer.lastName == secondPlayer.lastName {
        return firstPlayer.firstName < secondPlayer.firstName
    }
    return firstPlayer.lastName < secondPlayer.lastName
}
```

2024-11-20 04:24 UTC, LiyaNova commented on 10_FunctionalProgramming.playground/Contents.swift
> +func sortedArray(bocaJuniors: [FootballPlayer]) {
функцию, которая отсортирует массив на разные массивы по должностям 
Это значит, что тебе нужно принять массив, а вернуть двумерный массив. То есть оригинальный массив разбить на подмассивы по позициям игрока

func splitPlayersByPosition(footballTeam: [FootballPlayer]) -> [[FootballPlayer]]

Попробуешь еще раз?😉

2024-11-20 20:16 UTC, IvanKeyiOS commented on 10_FunctionalProgramming.playground/Contents.swift
> +let sortSureName: [FootballPlayer] = bocaJuniors.sorted { $0.name < $1.name }.sorted { $0.surename < $1.surename }
окей, на самом деле думал в данной домашней работе нужно применять новые знания полученные из урока, поэтому в сторону "if" не смотрел, но как оказалось нужно все применять что уже так или иначе знаешь, спасибо

2024-11-20 20:20 UTC, IvanKeyiOS commented on 10_FunctionalProgramming.playground/Contents.swift
> +func sortedArray(bocaJuniors: [FootballPlayer]) {
ага, окей, отличное уточние думал что нужны массивы, самодостаточные, а оказывается нужен массив массивов, спасибо

2024-11-20 22:13 UTC, IvanKeyiOS commented
Добрый вечер!

ой если честно прям даже не знаю что и сказать и не знаю как иначе сделать эту сортировку для массива массивов по позиции, исправил что-то, но очень сильно мне понравилось мое решение.

2024-11-21 03:38 UTC, LiyaNova approved these changes

2024-11-21 03:38 UTC, LiyaNova commented on 10_FunctionalProgramming.playground/Contents.swift
> +func sortedArray(bocaJuniors: [FootballPlayer]) -> [[FootballPlayer]]  {
Мысль уловил, молодец! Изящнее это можно было бы сделать так

```
func splitPlayersByPosition(footballTeam: [FootballPlayer]) -> [[FootballPlayer]] { 
    var result = [[FootballPlayer]]()

    for role in Position.allCases {
        let players = footballTeam.filter({ $0.playerPosition == role })
        result.append(players)
    }

    return result
}
```

2024-11-21 03:39 UTC, LiyaNova commented on 10_FunctionalProgramming.playground/Contents.swift
> +let sortSureName: [FootballPlayer] = bocaJuniors.sorted { $0.name < $1.name }.sorted { $0.surename < $1.surename }
Нужно применить решение согласно условию задачи 😉

2024-12-30 18:10 UTC, merged