Home workfifteen
IvanKeyiOS/homeWorks pull request #15
Opened 2024-12-07 19:05 UTC by IvanKeyiOS

2024-12-09 05:08 UTC, LiyaNova requested changes
Ваня, все отлично! Но предлагаю внести небольшое уточнение в логику одного заданию. Оставила комментарий 😉

2024-12-09 05:08 UTC, LiyaNova commented on 15_ProtocolExtension.playground/Contents.swift
> +extension EmployeeProtocol {
В extension необходимо добавить дефолтную реализацию для netSalary, новые свойства добавлять не нужно
Используй netSalary и grossSalary

2024-12-27 16:36 UTC, IvanKeyiOS commented on 15_ProtocolExtension.playground/Contents.swift
> +extension EmployeeProtocol {
extension EmployeeProtocol {
    var salaryNet: Int { return grossSalary - grossSalary * 21 / 100 }
}


таким образом?

2024-12-29 19:44 UTC, LiyaNova approved these changes

2024-12-30 18:10 UTC, merged